[package]
name = "fresh"
version = "0.0.0"
authors = ["Curtis McEnroe <june@causal.agency>"]
license = "AGPL-3.0-or-later"

[dependencies]
imap = "0.7.0"
rand = "0.4.2"
regex = "0.2.10"
reqwest = "0.8.5"
scraper = "0.6.0"
toml = "0.4.5"
xdg = "2.1.0"
