[package]
name = "fresh"
version = "0.1.0"
authors = ["Curtis McEnroe <programble@gmail.com>"]

[dependencies]
google-gmail1 = "0.1.9"
html5ever = "0.2.9"
hyper = "0.6.15"
rand = "0.3.12"
rustc-serialize = "0.3.16"
selectors = "0.2.1"
yup-oauth2 = "0.5.2"
