[package]
authors = ["Curtis McEnroe <programble@gmail.com>"]
name = "fresh"
version = "0.1.0"

[dependencies]
clap = "2.0.5"
google-gmail1 = "0.1.11"
hyper = "0.7.0"
inth-oauth2 = "0.7.0"
rand = "0.3.12"
rustc-serialize = "0.3.16"
scraper = "0.2.0"
url = "0.5.2"
xdg = "2.0.0"
yup-oauth2 = "0.5.3"
